#--------------------------------------------#
#
#	AVR Makefile suite
#	Author : Asif Mahmud Shimon
#	Usage : Easy to configure and to use Makefile 
#			suite for AVR platform using GNU 
#			Compiler suite.
#
#--------------------------------------------#
#--------configure the project sources-------#

#project title
TARGET = rfid


#source and header folder
SRC_FOLDER = src
BIN_FOLDER = bin
INCLUDE_FOLDER = src/include

#-----------C SOURCES------------------------#
C_SRC_FILES = main.c \
			lib/lcd.c \
			lib/mfrc522.c \
			lib/spi.c


#----------assembly sources------------------#
ASM_SRC_FILES = 

#--------------------------------------------#

#device configuration
DEVICE = atmega48
F_CPU  = 8000000
LFUSE  = 0xE7
HFUSE  = 0xD7
EFUSE  = 0x01

#preprocessors defines
DEFS  = 


#libraries to link
LD_FLAGS =

#programmer
#if in linux use sudo
SUDO = su
DUDE = avrdude
PROGRAMMER = usbasp


#-------Thats all needed---------------------#
