include Common

all :
	make -f $(MFile) all

program :
	make -f $(MFile) program
	
lfuse :
	make -f $(MFile) lfuse
	
hfuse :
	make -f $(MFile) hfuse
	
efuse :
	make -f $(MFile) efuse
	
program-all :
	make -f $(MFile) program-all
	
clean :
	make -f $(MFile) clean
